Resources:
  Assets:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.assetsBucketName}
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: [GET]
            AllowedOrigins: ["*"]

  # The policy that makes the bucket publicly readable
  AssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Assets # References the bucket we defined above
      PolicyDocument:
        Statement:
          -   Effect: Allow
              Principal: '*' # everyone
              Action: 's3:GetObject' # to read
              Resource: !Join ['/', [!GetAtt Assets.Arn, '*']] # things in the bucket
          # alternatively you can write out Resource: 'arn:aws:s3:::<bucket-name>/*'