# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Controller\Admin\CDNAssetsPackage:
        arguments:
            $requestStack: "@request_stack"
            $cdnBaseUrls:
                - '%env(ASSETS_BASE_URL)%/admin'

    Aws\DynamoDb\DynamoDbClient:
        class: Aws\DynamoDb\DynamoDbClient
        arguments:
            -
                region: '%env(AWS_STACK_REGION)%'
                endpoint: '%env(DYNAMO_DB_ENDPOINT)%'
                version: 'latest'

    session.dynamodb_handler:
        class: Aws\DynamoDb\SessionHandler
        factory: ['Aws\DynamoDb\SessionHandler', fromClient]
        arguments: ['@Aws\DynamoDb\DynamoDbClient', { table_name: '%env(SESSIONS_TABLE_NAME)%' }]

    App\Command\CreateDynamoDbSessionsTableCommand:
        arguments:
            $sessionsTableName: '%env(SESSIONS_TABLE_NAME)%'

when@prod:
    services:
        App\Controller\Admin\CDNAssetsPackage:
            decorates: EasyCorp\Bundle\EasyAdminBundle\Asset\AssetPackage
            arguments:
                $requestStack: "@request_stack"
                $cdnBaseUrls:
                    - '%env(ASSETS_BASE_URL)%/admin'
