version: '3.9'

services:
  web:
    image: docker.io/bref/fpm-dev-gateway:1.5.5
    container_name: scratch-dot-com-web
    ports:
      - 8080:80
    volumes:
      - ../app/public:/var/task/public:ro
    depends_on:
      - php
    networks:
      - app
    environment:
      HANDLER: public/index.php
      DOCUMENT_ROOT: public

  php:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: scratch-dot-com-php
    volumes:
      - ../app:/var/task:rw,delegated
    networks:
      - app
    depends_on:
      - mysql
      - dynamodb
    environment:
      APP_ENV: dev
      APP_SECRET: secret
      MAILER_DSN: 'smtp://mailhog:1025'
      MESSENGER_TRANSPORT_DSN: ~
      AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: eu-west-1

  mysql:
    image: mysql:8
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: scratch_db_pass
    networks:
      - app

  dynamodb:
    image: docker.io/amazon/dynamodb-local:1.18.0
    container_name: scratch-dot-com-dynamodb
    command:
      - '-jar'
      - 'DynamoDBLocal.jar'
      - '-inMemory'
      - '-sharedDb'
    ports:
      - "8000:8000"
    networks:
      - app

  node:
    image: node:14
    container_name: scratch-dot-com-node
    working_dir: /var/www/project
    volumes:
      - ../app:/var/www/project
    networks:
      - app

  mailhog:
    image: docker.io/mailhog/mailhog:v1.0.1
    container_name: scratch-dot-com-mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - app

networks:
  app:
