version: '3.9'

services:
  nginx:
    container_name: scratch-dot-com-nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ../app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - scratch_dot_com
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: scratch-dot-com-php
    volumes:
      - ../app:/var/www/project:rw,delegated
    networks:
      - scratch_dot_com
    ports:
      - '9000:9000'
    depends_on:
      - mysql
      - dynamodb
      - rabbitmq
    environment:
      APP_ENV: dev
      APP_SECRET: secret
      MAILER_DSN: 'smtp://mailhog:1025'
      MESSENGER_TRANSPORT_DSN: 'amqp://guest:guest@rabbitmq:5672/%2f/messages'
      AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: eu-west-1

  mysql:
    image: mysql:8
    container_name: scratch-dot-com-mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: scratch_db_pass
    networks:
      - scratch_dot_com

  dynamodb:
    image: docker.io/amazon/dynamodb-local:1.18.0
    container_name: scratch-dot-com-dynamodb
    command:
      - '-jar'
      - 'DynamoDBLocal.jar'
      - '-inMemory'
      - '-sharedDb'
    ports:
      - "8000:8000"
    networks:
      - scratch_dot_com

  node:
    image: node:14
    container_name: scratch-dot-com-node
    working_dir: /var/www/project
    volumes:
      - ../app:/var/www/project
    networks:
      - scratch_dot_com

  serverless:
    build:
      context: .
      dockerfile: sls.Dockerfile
    container_name: scratch-dot-com-serverless
    working_dir: /var/www/project
    volumes:
      - ../app:/var/www/project
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

  # Log in to the management console with guest:guest at http://localhost:15672/
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: scratch-dot-com-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
      - scratch_dot_com

networks:
  scratch_dot_com:
