service: scratch-dot-com

custom:
    dbUsername: 'SZaJ1DJKDcACk1y1' # should really use secrets manager for this
    dbPassword: 'Lo1okFQg0Ox4ufTe2X4M' # should really use secrets manager for this
    dbName: 'scratch_dot_com' # should really use secrets manager for this
    assetsBucketName: assets.scratch-dot-com

    s3Sync:
      # A simple configuration for copying static assets
      - bucketName: ${self:custom.assetsBucketName}
        localDir: public/build

provider:
    name: aws
    region: eu-west-1
    runtime: provided.al2
    environment:
        APP_ENV: prod
        ASSETS_BASE_URL: 'https://s3-eu-west-1.amazonaws.com/${self:custom.assetsBucketName}'
        DATABASE_URL:
            !Sub
            - 'mysql://${self:custom.dbUsername}:${self:custom.dbPassword}@${DB_ENDPOINT}:3306/${self:custom.dbName}?serverVersion=5.7&charset=utf8mb4'
            - { DB_ENDPOINT: !GetAtt 'RDSCluster.Endpoint.Address' }
    vpc:
        securityGroupIds:
            - !GetAtt ServerlessSecurityGroup.GroupId
        subnetIds:
            - !Ref ServerlessSubnetA
            - !Ref ServerlessSubnetB
            - !Ref ServerlessSubnetC

plugins:
  - ./vendor/bref/bref
  - serverless-s3-sync

functions:
    web: # don't forget to change this from the default 'api'
        handler: public/index.php # point to the Symfony front controller
        description: ''
        timeout: 60
        url: true # let's use a Lambda function URL so we always get the same URL, and better execution limits
        layers:
            - ${bref:layer.php-81-fpm}

    console:
        handler: bin/console # or 'artisan' for Laravel
        timeout: 600
        layers:
            - ${bref:layer.php-81} # PHP runtime
            - ${bref:layer.console} # Console layer

resources:
    - ${file(./serverless-config/network-resources.yml)}
    - ${file(./serverless-config/database-resources.yml)}
    - ${file(./serverless-config/s3-assets-resources.yml)}

# Exclude files from deployment
package:
    patterns:
        - '!node_modules/**'
        - '!tests/**'
